#!/usr/bin/env bash
# test-build-adapters.sh — Codex subagent TOML generation + per-CLI preambles.
#
# Hermetic by construction: each test copies the kit into $SANDBOX/kit and runs
# build-adapters.sh with HOME=$SANDBOX/home, so the real ~/.codex, ~/.copilot,
# and the repo's own models.yml are never read or written.

. "$(dirname -- "${BASH_SOURCE[0]}")/helpers.sh"

KIT_MARKER="# Generated by sdd-kit (build-adapters.sh) from models.yml — do not edit."

# stage_kit — kit copy in $SANDBOX/kit with a minimal models.yml; fresh
# $SANDBOX/home with .codex and .copilot. Echoes the kit path.
stage_kit() {
  local kit="$SANDBOX/kit"
  mkdir -p "$kit" "$SANDBOX/home/.codex" "$SANDBOX/home/.copilot"
  (cd "$KIT_DIR" && tar -cf - --exclude .git --exclude .specify --exclude '*.worktrees' .) \
    | (cd "$kit" && tar -xf -)
  write_policy_file "$kit"
  echo "$kit"
}

write_policy_file() {
  cat > "$1/models.yml" <<'EOF'
tiers:
  reasoning:
    codex_model: gpt-5.5
    codex_effort: xhigh
    codex_sandbox: workspace-write
    codex_approval: never
roles:
  opponent: reasoning
  reality-check: reasoning
  implement-hard: reasoning
  implement: reasoning
EOF
}

run_adapters() {  # <kit>
  env HOME="$SANDBOX/home" bash "$1/scripts/build-adapters.sh"
}

# AC-001: generated TOMLs carry the kit marker, identity, the role's tier
# model + effort, and the persona body as developer_instructions.
test_subagent_tomls_carry_identity_policy_and_persona() {
  local kit; kit="$(stage_kit)"
  local a="$SANDBOX/home/.codex/agents"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  local f
  for f in sdd-opponent sdd-reality-check sdd-implement-hard; do
    [[ -f "$a/$f.toml" ]] || t_fail "AC-001: missing $a/$f.toml"
  done
  assert_eq "$KIT_MARKER" "$(head -1 "$a/sdd-opponent.toml")" "AC-001: marker is line 1 (ownership test)"
  OUT="$(cat "$a/sdd-opponent.toml")"
  assert_contains "$OUT" 'name = "sdd-opponent"' "AC-001: name"
  assert_contains "$OUT" 'model = "gpt-5.5"' "AC-001: tier model stamped"
  assert_contains "$OUT" 'model_reasoning_effort = "xhigh"' "AC-001: tier effort stamped"
  assert_contains "$OUT" "developer_instructions = '''" "AC-001: instructions literal"
  assert_contains "$OUT" "devil" "AC-001: opponent persona body embedded"
  OUT="$(cat "$a/sdd-reality-check.toml")"
  assert_contains "$OUT" "last line of defense" "AC-001: reality-check persona body embedded"
  OUT="$(cat "$a/sdd-implement-hard.toml")"
  assert_contains "$OUT" "escalation implementer" "AC-001: inline implement-hard brief"
  assert_contains "$OUT" "Verify:" "AC-001: brief demands the Verify run"
}

# AC-002: an unmapped role's kit TOML is pruned on the next run; stale
# kit-marked TOMLs are pruned; user-authored TOMLs are never touched.
test_prune_respects_kit_marker_and_role_unmapping() {
  local kit; kit="$(stage_kit)"
  local a="$SANDBOX/home/.codex/agents"
  mkdir -p "$a"
  printf 'name = "mine"\n' > "$a/sdd-mine.toml"                # user file — NO marker
  printf '%s\nname = "old"\n' "$KIT_MARKER" > "$a/sdd-old.toml" # stale kit file
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  [[ -f "$a/sdd-implement-hard.toml" ]] || t_fail "AC-002: mapped role not generated"
  [[ -f "$a/sdd-mine.toml" ]] || t_fail "AC-002: user TOML deleted — must never happen"
  [[ -f "$a/sdd-old.toml" ]] && t_fail "AC-002: stale kit TOML survived the prune"
  # Unmap implement-hard → its TOML must be pruned by the next run.
  grep -v '^  implement-hard:' "$kit/models.yml" > "$kit/models.yml.tmp" \
    && mv "$kit/models.yml.tmp" "$kit/models.yml"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  assert_contains "$OUT" "skipped (role 'implement-hard' not in models.yml)" "AC-002: skip is announced"
  [[ -f "$a/sdd-implement-hard.toml" ]] && t_fail "AC-002: unmapped role's TOML not pruned"
  [[ -f "$a/sdd-mine.toml" ]] || t_fail "AC-002: user TOML deleted on re-run"
  [[ -f "$a/sdd-opponent.toml" ]] || t_fail "AC-002: still-mapped role lost its TOML"
}

# AC-003: no models.yml → no TOMLs, no error; no ~/.codex → nothing invented.
test_degrades_without_policy_or_codex_home() {
  local kit; kit="$(stage_kit)"
  rm "$kit/models.yml"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  [[ -e "$SANDBOX/home/.codex/agents/sdd-opponent.toml" ]] \
    && t_fail "AC-003: TOML written without models.yml"
  # ~/.codex absent entirely: adapters for copilot only, no .codex conjured.
  rm -rf "${SANDBOX:?}/home"; mkdir -p "$SANDBOX/home/.copilot"
  write_policy_file "$kit"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  [[ -d "$SANDBOX/home/.codex" ]] && t_fail "AC-003: .codex created when absent"
  [[ -f "$SANDBOX/home/.copilot/agents/sdd-implement.agent.md" ]] \
    || t_fail "AC-003: copilot adapters should still build"
}

# AC-004: codex adapters carry the delegation preamble; copilot adapters keep
# the persona-pass preamble.
test_codex_adapters_delegate_copilot_adapters_persona_pass() {
  local kit; kit="$(stage_kit)"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  OUT="$(cat "$SANDBOX/home/.codex/skills/sdd-implement/SKILL.md")"
  assert_contains "$OUT" "sdd-opponent" "AC-004: codex gates delegated"
  assert_contains "$OUT" "sdd-implement-hard" "AC-004: codex escalation delegated"
  assert_contains "$OUT" "fall back" "AC-004: persona-pass fallback stated"
  assert_contains "$OUT" 'agent_type' \
    "AC-004: preamble names the agent_type spawn field (task_name alone runs a generic child)"
  assert_not_contains "$OUT" "Single-agent adaptation" "AC-004: stale claim gone from codex"
  OUT="$(cat "$SANDBOX/home/.copilot/agents/sdd-implement.agent.md")"
  assert_contains "$OUT" "Single-agent adaptation" "AC-004: copilot keeps persona-pass"
  assert_contains "$OUT" "does not yet wire delegation" "AC-004: copilot preamble is honest about why"
  assert_not_contains "$OUT" "sdd-implement-hard" "AC-004: copilot promises no delegation"
}

# AC-006: no stale "no subagents on Codex" claim survives in the four doc
# surfaces; the corrected sections name the generated subagents.
test_stale_single_agent_claims_are_gone() {
  local f
  for f in agents/opponent.agent.md agents/reality-check.agent.md constitution.md README.md; do
    OUT="$(cat "$KIT_DIR/$f")"
    assert_not_contains "$OUT" "without subagents" "AC-006: stale claim survives in $f"
    assert_not_contains "$OUT" "there is no subagent to spawn" "AC-006: stale claim survives in $f"
    assert_not_contains "$OUT" "Single-agent note" "AC-006: stale heading survives in $f"
  done
  OUT="$(cat "$KIT_DIR/constitution.md")"
  assert_contains "$OUT" "codex/agents" "AC-006: constitution names the subagent path"
  OUT="$(cat "$KIT_DIR/README.md")"
  assert_contains "$OUT" "sdd-reality-check" "AC-006: README names the generated gates"
}

# AC-007 / AC-008: the empirical findings are pinned as a versioned knowledge
# artifact — both CLIs carry a dated, version-stamped Finding line, so the
# claims the docs make trace to captured probes (transcripts in the spec's
# notes/), not to memory.
test_delegation_findings_artifact_present_and_shaped() {
  local k="$KIT_DIR/knowledge/cli-subagent-delegation.md"
  [[ -f "$k" ]] || { t_fail "AC-007/AC-008: knowledge/cli-subagent-delegation.md missing"; return; }
  OUT="$(cat "$k")"
  assert_contains "$OUT" "Codex CLI (codex-cli 0.144" "AC-007: codex finding is version-stamped"
  assert_contains "$OUT" "Copilot CLI (1.0" "AC-008: copilot finding is version-stamped"
  local n
  n="$(grep -c '^\*\*Finding:' "$k")"
  assert_eq 2 "$n" "AC-007/AC-008: one Finding verdict per CLI"
  assert_contains "$OUT" "NOT honored" "AC-007: the codex model-pin delta is recorded, not papered over"
}

# Multi-home: adapters land in EVERY codex home — ~/.codex plus any ~/.codex_*
# directory (the `CODEX_HOME=~/.codex_gym codex` pattern). The kit-marker
# ownership rule extends to tier profile files: one Codex itself wrote state
# into (no marker) is never overwritten or pruned; per-home prune still works.
test_adapters_install_into_every_codex_home() {
  local kit; kit="$(stage_kit)"
  mkdir -p "$SANDBOX/home/.codex_gym"
  : > "$SANDBOX/home/.codex_notadir"   # FILE matching the glob — must be ignored
  printf 'model = "user-pinned"\n[projects."/x"]\ntrust_level = "trusted"\n' \
    > "$SANDBOX/home/.codex_gym/sdd-reasoning.config.toml"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  local h
  for h in .codex .codex_gym; do
    [[ -f "$SANDBOX/home/$h/skills/sdd-implement/SKILL.md" ]] \
      || t_fail "multi-home: $h missing skill adapter"
    [[ -f "$SANDBOX/home/$h/agents/sdd-opponent.toml" ]] \
      || t_fail "multi-home: $h missing subagent TOML"
  done
  assert_eq "$KIT_MARKER" "$(head -1 "$SANDBOX/home/.codex/sdd-reasoning.config.toml")" \
    "multi-home: primary home tier profile generated"
  OUT="$(cat "$SANDBOX/home/.codex/sdd-reasoning.config.toml")"
  assert_contains "$OUT" 'sandbox_mode = "workspace-write"' \
    "profile: codex_sandbox stamped as sandbox_mode"
  assert_contains "$OUT" 'approval_policy = "never"' \
    "profile: codex_approval stamped as approval_policy (subagents inherit the session policy)"
  OUT="$(cat "$SANDBOX/home/.codex_gym/sdd-reasoning.config.toml")"
  assert_contains "$OUT" 'user-pinned' "multi-home: non-kit profile file was clobbered"
  assert_not_contains "$OUT" "Generated by sdd-kit" "multi-home: non-kit profile file re-stamped"
  [[ -f "$SANDBOX/home/.codex_notadir" && ! -d "$SANDBOX/home/.codex_notadir" ]] \
    || t_fail "multi-home: glob-matching plain file mishandled"
  # prune is per home: a stale kit-marked TOML in the extra home goes away,
  # while the freshly generated ones stay.
  printf '%s\nname = "old"\n' "$KIT_MARKER" > "$SANDBOX/home/.codex_gym/agents/sdd-old.toml"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  [[ -f "$SANDBOX/home/.codex_gym/agents/sdd-old.toml" ]] \
    && t_fail "multi-home: stale kit TOML survived prune in extra home"
  [[ -f "$SANDBOX/home/.codex_gym/agents/sdd-opponent.toml" ]] \
    || t_fail "multi-home: live subagent TOML lost on re-run"
}

t_run_all
