#!/usr/bin/env bash
# test-build-adapters.sh — Codex subagent TOML generation + per-CLI preambles.
#
# Hermetic by construction: each test copies the kit into $SANDBOX/kit and runs
# build-adapters.sh with HOME=$SANDBOX/home, so the real ~/.codex, ~/.copilot,
# and the repo's own models.yml are never read or written.

. "$(dirname -- "${BASH_SOURCE[0]}")/helpers.sh"

KIT_MARKER="# Generated by sdd-kit (build-adapters.sh) from models.yml — do not edit."

# stage_kit — kit copy in $SANDBOX/kit with a minimal models.yml; fresh
# $SANDBOX/home with .codex and .copilot. Echoes the kit path.
stage_kit() {
  local kit="$SANDBOX/kit"
  mkdir -p "$kit" "$SANDBOX/home/.codex" "$SANDBOX/home/.copilot"
  (cd "$KIT_DIR" && tar -cf - --exclude .git --exclude .specify --exclude '*.worktrees' .) \
    | (cd "$kit" && tar -xf -)
  write_policy_file "$kit"
  echo "$kit"
}

write_policy_file() {
  cat > "$1/models.yml" <<'EOF'
tiers:
  reasoning:
    codex_model: gpt-5.5
    codex_effort: xhigh
roles:
  opponent: reasoning
  reality-check: reasoning
  implement-hard: reasoning
  implement: reasoning
EOF
}

run_adapters() {  # <kit>
  env HOME="$SANDBOX/home" bash "$1/scripts/build-adapters.sh"
}

# AC-001: generated TOMLs carry the kit marker, identity, the role's tier
# model + effort, and the persona body as developer_instructions.
test_subagent_tomls_carry_identity_policy_and_persona() {
  local kit; kit="$(stage_kit)"
  local a="$SANDBOX/home/.codex/agents"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  local f
  for f in sdd-opponent sdd-reality-check sdd-implement-hard; do
    [[ -f "$a/$f.toml" ]] || t_fail "AC-001: missing $a/$f.toml"
  done
  assert_eq "$KIT_MARKER" "$(head -1 "$a/sdd-opponent.toml")" "AC-001: marker is line 1 (ownership test)"
  OUT="$(cat "$a/sdd-opponent.toml")"
  assert_contains "$OUT" 'name = "sdd-opponent"' "AC-001: name"
  assert_contains "$OUT" 'model = "gpt-5.5"' "AC-001: tier model stamped"
  assert_contains "$OUT" 'model_reasoning_effort = "xhigh"' "AC-001: tier effort stamped"
  assert_contains "$OUT" "developer_instructions = '''" "AC-001: instructions literal"
  assert_contains "$OUT" "devil" "AC-001: opponent persona body embedded"
  OUT="$(cat "$a/sdd-reality-check.toml")"
  assert_contains "$OUT" "last line of defense" "AC-001: reality-check persona body embedded"
  OUT="$(cat "$a/sdd-implement-hard.toml")"
  assert_contains "$OUT" "escalation implementer" "AC-001: inline implement-hard brief"
  assert_contains "$OUT" "Verify:" "AC-001: brief demands the Verify run"
}

# AC-002: an unmapped role's kit TOML is pruned on the next run; stale
# kit-marked TOMLs are pruned; user-authored TOMLs are never touched.
test_prune_respects_kit_marker_and_role_unmapping() {
  local kit; kit="$(stage_kit)"
  local a="$SANDBOX/home/.codex/agents"
  mkdir -p "$a"
  printf 'name = "mine"\n' > "$a/sdd-mine.toml"                # user file — NO marker
  printf '%s\nname = "old"\n' "$KIT_MARKER" > "$a/sdd-old.toml" # stale kit file
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  [[ -f "$a/sdd-implement-hard.toml" ]] || t_fail "AC-002: mapped role not generated"
  [[ -f "$a/sdd-mine.toml" ]] || t_fail "AC-002: user TOML deleted — must never happen"
  [[ -f "$a/sdd-old.toml" ]] && t_fail "AC-002: stale kit TOML survived the prune"
  # Unmap implement-hard → its TOML must be pruned by the next run.
  grep -v '^  implement-hard:' "$kit/models.yml" > "$kit/models.yml.tmp" \
    && mv "$kit/models.yml.tmp" "$kit/models.yml"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  assert_contains "$OUT" "skipped (role 'implement-hard' not in models.yml)" "AC-002: skip is announced"
  [[ -f "$a/sdd-implement-hard.toml" ]] && t_fail "AC-002: unmapped role's TOML not pruned"
  [[ -f "$a/sdd-mine.toml" ]] || t_fail "AC-002: user TOML deleted on re-run"
  [[ -f "$a/sdd-opponent.toml" ]] || t_fail "AC-002: still-mapped role lost its TOML"
}

# AC-003: no models.yml → no TOMLs, no error; no ~/.codex → nothing invented.
test_degrades_without_policy_or_codex_home() {
  local kit; kit="$(stage_kit)"
  rm "$kit/models.yml"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  [[ -e "$SANDBOX/home/.codex/agents/sdd-opponent.toml" ]] \
    && t_fail "AC-003: TOML written without models.yml"
  # ~/.codex absent entirely: adapters for copilot only, no .codex conjured.
  rm -rf "${SANDBOX:?}/home"; mkdir -p "$SANDBOX/home/.copilot"
  write_policy_file "$kit"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  [[ -d "$SANDBOX/home/.codex" ]] && t_fail "AC-003: .codex created when absent"
  [[ -f "$SANDBOX/home/.copilot/agents/sdd-implement.agent.md" ]] \
    || t_fail "AC-003: copilot adapters should still build"
}

# AC-004: codex adapters carry the delegation preamble; copilot adapters keep
# the persona-pass preamble.
test_codex_adapters_delegate_copilot_adapters_persona_pass() {
  local kit; kit="$(stage_kit)"
  run_rc 0 env HOME="$SANDBOX/home" bash "$kit/scripts/build-adapters.sh"
  OUT="$(cat "$SANDBOX/home/.codex/skills/sdd-implement/SKILL.md")"
  assert_contains "$OUT" "sdd-opponent" "AC-004: codex gates delegated"
  assert_contains "$OUT" "sdd-implement-hard" "AC-004: codex escalation delegated"
  assert_contains "$OUT" "fall back" "AC-004: persona-pass fallback stated"
  assert_not_contains "$OUT" "You are running on a CLI without subagents" "AC-004: stale claim gone from codex"
  OUT="$(cat "$SANDBOX/home/.copilot/agents/sdd-implement.agent.md")"
  assert_contains "$OUT" "You are running on a CLI without subagents" "AC-004: copilot keeps persona-pass"
  assert_not_contains "$OUT" "sdd-implement-hard" "AC-004: copilot promises no delegation"
}

t_run_all
